SCR_MissionHeader {
 World "{20A6277F69EB918B}worlds/TheLocalPub/TableTopTroopers/TableTopTroopers.ent"
 m_sName "TVT (4-50) Table Top Troopers"
 m_sAuthor "TheLocalPub"
 m_sDescription "A British platoon must defend CIMIC House against a large-scale Iraqi assault aimed at overrunning and capturing the compound."\
 "Can the garrison hold long enough to force the attackers to withdraw?"
 m_sDetails "A British platoon must defend CIMIC House against a large-scale Iraqi assault aimed at overrunning and capturing the compound."\
 "Can the garrison hold long enough to force the attackers to withdraw?"
 m_iPlayerCount 36
 m_iStartingHours 12
}