SCR_MissionHeader {
 World "{165849BE88055BC8}worlds/TheLocalPub/TrackMania/TrackMania.ent"
 m_sName "LOL (2-79) Track Mania"
 m_sAuthor "TheLocalPub"
 m_sDescription "The annual Track Mania race has come to Ruha. Who'll take home the cup and claim victory this year?"\
 ""
 m_sDetails "The annual Track Mania race has come to Ruha. Who'll take home the cup and claim victory this year?"\
 ""
 m_iPlayerCount 79
 m_iStartingHours 15
}